### PR TITLE
Round 0 ICM submission

### PR DESCRIPTION
**Pull request by macrad**

### CODE REVIEW

**Comment by kathsherratt** [comment]
Hi @macrad , thank you for submitting! 

I can see you've submitted point projections which have valid values, so that's fine. 

To stop the check from failing, you would just need to remove the rows where `value` is `NA`. I think this is where you've included rows for each possible quantile, without a projected value. 

If that sounds right to you, then don't worry about it this round, we can edit it at our end this time so you don't need to do anything further. 

Thanks again!
Kath

cc @Bisaloo

**Comment by macrad** [comment]
Hi @kathsherratt,

thank you for the tip! Next time we'll make sure to commit completely valid file, hopefully with quantiles.

Best regards,
Maciek

**Comment by macrad** [comment]
Hi @kathsherratt,

Another question: where should we put models/scenarios abstract?

Best regards,
Maciek

**Comment by kathsherratt** [comment]
Hi Maciek, please could you add the abstract to the same folder `data-processed/team-model` as you have with your other files? Thank you so much!

**Pull request merged**
