### PR TITLE
USC-SIkJalpha Round 2 submission

### PR DESCRIPTION
**Pull request by scc-usc**

### CODE REVIEW

**Comment by Bisaloo** [comment]
Hi @scc-usc, thanks for contributing. 

There is a merge conflict with the metadata file because we updated some fields (e.g., `model_contributors` now contains a structured list of authors, with email and affiliations) and renamed the file to `metadata-USC-SIkJalpha.yml`. It's entirely my fault so I can fix it for you if you wish.

**Comment by scc-usc** [comment]
Hi @Bisaloo. It will be great if you could make that change. Thanks!

**Comment by Bisaloo** [comment]
I fixed it locally but it looks like I cannot push because I don't have write access on your fork. 

Could you [allow edits from maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) please?

**Comment by Bisaloo** [comment]
Submission merged in https://github.com/covid19-forecast-hub-europe/covid19-scenario-hub-europe/commit/d878a28315a6ea3a103e53595854b376f9053cd6.

**Pull request closed without merging**
