### PR TITLE
RIVM-vacamole round 2 results submission

### PR DESCRIPTION
**Pull request by kylieainslie**

### CODE REVIEW

**Comment by kylieainslie** [comment]
Error seems to be that the scenario_id names don't match, but I've double checked and they do match, so not sure why validation is throwing an error.

**Comment by Bisaloo** [comment]
Oh right, it's my fault, sorry. Validations run on the entire repo (including the new submission for your PR) so it tries to validate the round 1 submission as well, as the `scenario_id` don't match.

Please leave me a moment to fix it. Your submission is fine when I validate it locally so no further action should be required from your end :slightly_smiling_face:

**Comment by Bisaloo** [comment]
Oh scratch that, there seems to be a problem with your `target_end_date`, which is always `2023-07-24` when it should be roughly `origin_date` + `horizon`.

If that's helpful, you can see how Kath fixed it for your round 1 submission: https://github.com/covid19-forecast-hub-europe/covid19-scenario-hub-europe/pull/40.

**Comment by kylieainslie** [comment]
Thanks @Bisaloo! I'll fix the target_end_date. I think I misunderstood what should go in that variable!

**Comment by kylieainslie** [comment]
@Bisaloo my branch should be ready to merge. Still getting the original error that I mentioned earlier, so flagging it so you can validate it locally. Would it be better to remove old files from the data-processed folder?

**Pull request merged**
